Add click handler
matheus-fls/calculatoReact pull request #5
Opened 2020-01-16 21:26 UTC by matheus-fls

2020-01-17 17:55 UTC, shloch requested changes
## hello @matheus-fls 
Works perfectly, i like your display... its very cool

You have not managed division by ZERO
![Screenshot from 2020-01-17 18-50-40](https://user-images.githubusercontent.com/40712459/72634155-538fe300-395a-11ea-9d0a-766c9725132c.png)

Please solve the issue above, and the one mentioned below, and file for last review hopefully 🙂🙂

2020-01-17 17:55 UTC, shloch commented on src/components/App.js
> +    }
most of this logic should be inside the `"src/logic/calculate.js"` . Thats why we have a logic folder. When you'll should call it here

send it there

2020-01-17 23:20 UTC, matheus-fls commented
Hello Shey, thank you very much for your review.

I believe I did all the required changes. If I forgot something or if there are more issues to be solved please let me know.

2020-01-20 08:36 UTC, bolah2009 approved these changes
It's a 👍🏾 from me!

### :heavy_check_mark: Approved!

Good luck with your next project. :star2: 

Cheers
[Bola](https://bolabuari.com/)

2020-01-20 17:27 UTC, merged